ALTER TABLE flyer_deals
    ADD COLUMN IF NOT EXISTS store_id  INTEGER REFERENCES store_locations(id),
    ADD COLUMN IF NOT EXISTS store_lat DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS store_lng DOUBLE PRECISION;